# Generated by Django 4.0.3 on 2022-03-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.CharField(default='author', max_length=255, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
